### ISSUE TITLE
Allow to pass a github token

### ISSUE THREAD

**Issue by caarlos0** [arduino/setup-task#223]
I'm getting quite a bit of this:

> API rate limit exceeded for 199.19.85.26. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

Maybe we should allow to pass a `GITHUB_TOKEN` and auth with it?

**Comment by per1234** [comment]
Hi @caarlos0. This is already possible to do via the action's `repo-token` input:
https://github.com/arduino/setup-task#repo-token
We use `${{ secrets.GITHUB_TOKEN }}` with this input in all our workflows and never have a single problem with rate limiting.
