### ISSUE TITLE
node 20 update

### ISSUE THREAD

**Issue by blade2005** [arduino/setup-task#918]
### Describe the problem

Warnings about EOL for node.js 16 actions

! Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: arduino/setup-task@v1.0.3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### To reproduce

Use the action anywhere and you'll see the annotation 

### Expected behavior

run on node 20

### 'arduino/setup-task' version

v1.0.3

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/setup-task/issues?q=)
- [X] I verified the problem still occurs when using the latest version
- [X] My report contains all necessary details

**Comment by alessio-perugini** [comment]
Many thanks to @gdraynz , we have now published the new release: https://github.com/arduino/setup-task/releases/tag/v2.0.0
